name: Cache Workflow Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-697a099

      - name: prime-cache-697a099
        run: echo "Cache ${{ steps.cache.outputs.cache-hit }}"
