name: Email Step Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 23f2000689@ds.study.iitm.ac.in
        run: |
          echo "This step's name contains the required email address."
          echo "Hello, world!"

